### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hartenthaler** [jpretired/jp-main-menu-item#1]
Good idea!

Maybe:
- detect the language of user/browser and adjust link to English/Czech version of manual
- add submenu with link to standard webtrees Docs and FAQ
> https://webtrees.net/install/
> https://webtrees.net/faq/
> ...

**Comment by jpretired** [comment]
Thank you for suggestions.

1. I shall try this
2. there is a link to webtrees.net at the bottom of a page

**Comment by jpretired** [comment]
Included in v1.0.6
